Added new action GetCatalogsAction
JavaOnePercent/liquid-log pull request #2
Opened 2017-10-30 19:22 UTC by JavaOnePercent

2017-10-30 19:23 UTC, JavaOnePercent commented
@ykalemi Прошу проверить

2017-10-31 03:21 UTC, ykalemi requested changes
верните в исходное состояние application.properties - и тогда все ок

2017-10-31 03:21 UTC, ykalemi commented on src/main/resources/application.properties
> +influx.host=http://wildfly-influxdb-myliquitlog.148.251.87.70.nip.io
этот файл не нужно было изменять. Посмотрите инструкцию (readme), нужно было создать копию файла и положить в папку config

сейчас получается, что весь интернет знает ваш логин и пароль

2017-10-31 03:21 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/influx/InfluxDAO.java
> +                .addField(CATALOGS_ACTION, dones.getCatalogsAction()) //новое действие
такие комментарии лучше не оставлять в коде. Через неделю это действие не будет новым, и комментарии только мешают

2017-10-31 16:32 UTC, merged