task 3
JavaOnePercent/liquid-log pull request #4
Opened 2017-11-15 00:28 UTC by JavaOnePercent

@ykalemi Прошу проверить

2017-11-16 13:02 UTC, ykalemi requested changes
В целом всё выглядит хорошо. Только мне кажется или вы не запускали, или сделали какие-то изменения в последний момент :) Есть одно замечание по app

2017-11-16 13:02 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +            app.parser(namedb, parsingmode, timezone, logresult, file);
здесь вы вызываете статический метод класса, но обращаетесь к объекту. Две проблемы:
- надо явно обращаться к классу, потому что статический метод - это именно метод класса. Так код чище
- объект app у вас в коде не проинициализирован, так что здесь просто будет NullPointerException

2017-11-16 13:02 UTC, ykalemi commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +        model.put("parsing", clientParsing);
это задел на будущее? Просто эта Map вроде бы нигде не заполняется и всегда пустая

2017-11-16 15:12 UTC, JavaOnePercent commented on src/main/java/ru/naumen/perfhouse/controllers/ClientsController.java
> +            app.parser(namedb, parsingmode, timezone, logresult, file);
Исправил

2017-11-17 06:31 UTC, ykalemi approved these changes

2017-11-17 07:13 UTC, merged